x=int(input("Enter the number1 "))
y=int(input("Enter the number2 "))
print("Addition:"+str(x+y))
print("Subtraction:"+str(x-y))
print("Multiplication:"+str(x*y))
print("Division:"+str(x/y))
print("Modulus:"+str(x%y))
print("Exponentiation:"+str( x**y))
print("Floor division:"+str(x//y))