id=1001
name="saran"
grade="10A"
nic=200634201095
print("--------------")
print("student Information")
print("--------------")
print("student id is:",id,"\nstudent name is ",name,"\nstudent grade is ",grade,"\nstudent NIC number is ",nic)
print("--------------")
print("***************")
print("--------------")
print("student Information")
print("--------------")
output=f"student name is {name}\nstudent id is {id}\nstudent grade is {grade} \nstudent NIC number is {nic}"
print(output)
print("--------------")
print("**********")
print("--------------")
print("student Information")
print("--------------")
output="student name is {0}\nstudent id is {1}\nstudent grade is {2} \nstudent NIC number is {3}".format(name,id,grade,nic)
print(output)
print("--------------")
print("**********")
print("--------------")
print("student Information")
print("--------------")
print("student name is %s \nstudent id is %d \nstudent grade is %s \nstudent NIC number is %d"%(name,id,grade,nic))
print("--------------")
print("***************")
print("--------------")
print("student Information")
print("--------------")
print("student id is"+str(id),"\nstudent name is "+name,"\nstudent grade is "+grade,"\nstudent NIC number is"+str(nic))
print("--------------")
