name=input("Enter your name")
age=int(input("Enter your age"))
print("Enter your 5 marks")
m1=int(input("Enter the marks1: "))
m2=int(input("Enter the marks2: "))
m3=int(input("Enter the marks3: "))
m4=int(input("Enter the marks4: "))
m5=int(input("Enter the marks5: "))
total=m1+m2+m3+m4+m5
average=total/5
print("your name is : "+name)
print("your age is : "+str(age))
print("this is your marks1 :"+str(m1))
print("this is your marks2 :"+str(m2))
print("this is your marks3 :"+str(m3))
print("this is your marks4 :"+str(m4))
print("this is your marks5 :"+str(m5))
print("this is your total :"+str(total))
print("this is your average :"+str(average ))